import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import localFont from "next/font/local";

// import Script from "next/script";
import "./globals.css";

// const fontIsidora = localFont({
//   src: [{ path: "../../public/IsidoraSans-Medium.otf", weight: "600" }],
// });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        // className={`${fontIsidora.className} antialiased`}
      >
        {children}

        <link
          href="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.css"
          rel="stylesheet"
        />

        <script
          defer
          src="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.js"
        ></script>
      </body>
    </html>
  );
}
